### PR TITLE
Add vod method to get SIP information

### PR DESCRIPTION
**Pull request by mrose17**
the first step to getting real-time video from a doorbell/camera!

### CODE REVIEW

**Comment by davglass** [comment]
Ha! That's funny..

**Comment by mrose17** [comment]
actually the *fun* part is going to be doing the SIP/SDP dance to get an actual stream...

**Comment by davglass** [comment]
@mrose17 Adding these tests should pass the build:

```js
it('start vod with error', (done) => {
        nock('https://api.ring.com').post('/clients_api/doorbots/1/vod')
            .query({ auth_token: 'TOKEN', api_version: 9 })
            .reply(200, {
            });
        nock('https://api.ring.com').get('/clients_api/dings/active')
            .query({ auth_token: 'TOKEN', api_version: 9 })
            .reply(200, []);
        const ring = RingAPI({
            username: 'test',
            password: 'test'
        });
        ring.token = 'TOKEN';
        ring.vod({ id: 1 }, (e) => {
            assert.ok(e);
            done();
        });
    });

    it('start vod with vod error', (done) => {
        nock('https://api.ring.com').post('/clients_api/doorbots/1/vod')
            .query({ auth_token: 'TOKEN', api_version: 9 })
            .reply(500, {
                error: new Error('Borked')
            });
        const ring = RingAPI({
            username: 'test',
            password: 'test'
        });
        ring.token = 'TOKEN';
        ring.vod({ id: 1 }, (e) => {
            assert.ok(e);
            done();
        });
    });
    
    it('start vod with ding error', (done) => {
        nock('https://api.ring.com').post('/clients_api/doorbots/1/vod')
            .query({ auth_token: 'TOKEN', api_version: 9 })
            .reply(200, {
            });
        nock('https://api.ring.com').get('/clients_api/dings/active')
            .query({ auth_token: 'TOKEN', api_version: 9 })
            .reply(500, {
                error: new Error('Borked')
            });
        const ring = RingAPI({
            username: 'test',
            password: 'test'
        });
        ring.token = 'TOKEN';
        ring.vod({ id: 1 }, (e) => {
            assert.ok(e);
            done();
        });
    });
```

**Comment by davglass** [comment]
Merged, do you want me to cut a release for this? Or wait until you've worked out the SIP song and dance?

**Comment by mrose17** [comment]
thanks. if you cut a new release, that'd be nice. not urgent though.

**Pull request merged**
